let $VIMDIR=expand($HOME)."/.vim"
let $VIMRC="$VIMDIR/vimrc"

" Load plugins
source $VIMDIR/plugins.vim

" Load VIM Configurations
source $VIMDIR/configs.vim

" Load Keybindings
source $VIMDIR/key_maps.vim

" Load plugin configurations
source $VIMDIR/plugin_config.vim

" Load Autocommand
source $VIMDIR/autocommands.vim

" Save session files to $HOME/.vim/session directory
let g:session_dir="$VIMDIR/session"

""""""""""""""""""""""""""""""""
"
" THEME
"
""""""""""""""""""""""""""""""""
let g:lightline = { 'colorscheme': 'catppuccin_mocha' }
colorscheme catppuccin_mocha

""""""""""""""""""""""""""""""""
"
" VIM SPECIFIC CONFIG
"
""""""""""""""""""""""""""""""""

" Move the .viminfo file inside .vim directory
set viminfofile=$VIMDIR/viminfo

" Auto reload .vimrc
autocmd! bufwritepost $VIMRC source %

" Save inside vim config directory
set undodir=$VIMDIR/undo//

" Ctrl+Backspace to add an undo-point and delete last word
" It's here cause ideavim messes it up
imap <C-BS> <C-g>u<C-w>

" Map nerdtree to <Leader>e
" Changes the pwd and opens the VCS root
" Placed here because ideavim doesn't understand :tcd
nnoremap <leader>e :tcd %:h<CR> :NERDTreeToggleVCS<CR>
