#!/bin/sh

# Check if Gitleaks is installed
if ! command -v gitleaks >/dev/null 2>&1; then
    echo "Gitleaks is not installed. Skipping leak check."
    echo "Please install Gitleaks for enhanced security."
    exit 0
fi

# Run Gitleaks & check the exit code
if ! gitleaks protect --staged -v; then
    echo "Gitleaks has detected potential secrets in your changes."
    echo "Please remove any sensitive information before committing."
    exit 1
fi

# If Gitleaks passes, allow the commit
exit 0
