-- Required mostly be lualine plugin
-- Copied from Lazyvim
local M = {
    icons = {
        misc = {
            dots = "󰇘",
            timer = "󰔟",
        },
        dap = {
            Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
            Breakpoint = " ",
            BreakpointCondition = " ",
            BreakpointRejected = { " ", "DiagnosticError" },
            LogPoint = ".>",
        },
        diagnostics = { ERROR = " ", WARN = " ", HINT = " ", INFO = " " },
        git = { added = " ", modified = " ", removed = " " },
        kinds = {
            Array = " ",
            Boolean = "󰨙 ",
            Class = " ",
            Codeium = "󰘦 ",
            Color = " ",
            Control = " ",
            Collapsed = " ",
            Constant = "󰏿 ",
            Constructor = " ",
            Copilot = " ",
            Enum = " ",
            EnumMember = " ",
            Event = " ",
            Field = " ",
            File = "󰈙 ",
            Folder = " ",
            Function = "󰡱 ",
            Interface = " ",
            Key = "󰌋 ",
            Keyword = " ",
            Method = "󰡱 ",
            Module = " ",
            Namespace = "󰦮 ",
            Null = "󰟢 ",
            Number = "󰎠 ",
            Object = " ",
            Operator = " ",
            Package = " ",
            Property = " ",
            Reference = " ",
            Snippet = " ",
            String = " ",
            Struct = " ",
            TabNine = "󰏚 ",
            Text = " ",
            TypeParameter = " ",
            Unit = " ",
            Value = " ",
            Variable = "󰀫 ",
        },
        -- Only to keep things in sync with "navbuddy"
        kind_lspsaga = {
            ["Array"] = { " ", "Type" },
            ["Boolean"] = { "󰨙 ", "Boolean" },
            ["Class"] = { " ", "Include" },
            ["Constant"] = { "󰏿 ", "Constant" },
            ["Constructor"] = { " ", "@constructor" },
            ["Enum"] = { " ", "@number" },
            ["EnumMember"] = { " ", "Number" },
            ["Event"] = { " ", "Constant" },
            ["Field"] = { " ", "@field" },
            ["File"] = { "󰈙 ", "Tag" },
            ["Function"] = { "󰡱 ", "Function" },
            ["Interface"] = { " ", "Type" },
            ["Key"] = { "󰌋 ", "Constant" },
            ["Method"] = { "󰡱 ", "Function" },
            ["Module"] = { " ", "Exception" },
            ["Namespace"] = { "󰦮 ", "Include" },
            ["Null"] = { "󰟢 ", "Constant" },
            ["Number"] = { "󰎠 ", "Number" },
            ["Object"] = { " ", "Type" },
            ["Operator"] = { " ", "Operator" },
            ["Package"] = { " ", "Label" },
            ["Property"] = { " ", "@property" },
            ["String"] = { " ", "String" },
            ["Struct"] = { " ", "Type" },
            ["TypeParameter"] = { " ", "Type" },
            ["Variable"] = { "󰀫 ", "@variable" },
            -- ccls
            ["TypeAlias"] = { " ", "Type" },
            ["Parameter"] = { " ", "@parameter" },
            ["StaticMethod"] = { "󰡱 ", "Function" },
            ["Macro"] = { " ", "Macro" },
            -- for completion sb microsoft!!!
            ["Text"] = { "󰭷 ", "String" },
            ["Snippet"] = { " ", "@variable" },
            ["Folder"] = { " ", "Title" },
            ["Unit"] = { "󰊱 ", "Number" },
            ["Value"] = { "󰀫 ", "@variable" },
        },
    },
}
return M
